export const HOME = '/';
export const LOGIN = '/Login';
export const SIGNUP: any = '/signup';
export const FORGOTPASSWORD = "/forgot-password";
export const VERIFYEMAIL = "/verify/email"
export const VERIFYEMAILPOPUP = "/verify/emailpopup"
export const MEMBERSHIP = "/membership"
// export const FORGETPASSWORD = "/forget-password";
export const COMPANY_SIGNUP = "/company/login";
export const CHECKMAIL = "/check-mail";
export const SETPASSWORD = "/new/password";
export const QUICK_SCREENS = "/quick/screens";
export const COURSE = "/course"
export const COURSEDETAILS: any = "/course/detail/"
export const COURSEVIEW: any = "/course/view/"
export const LOGINPOPUP = "/login/popup"
export const SIGNUPPOPUP = "/signup/popup"
export const BUYCOURSEDETAIL = "/buy/course"
export const BUYCOURSE = "/buy/course/payment"
export const ASKANURSE = "/ask_a_nurse"
export const LIVEEVENT = '/live-event';
export const FAQLIST = "/ask_a_nurse/faq-list/"
export const NURSECHAT = "/ask_a_nurse/chat"
export const INSTRUCTOR = "/instructor/";
export const EVENTS = "/events";
export const EVENTSDETAIL = "/events/detail/";
export const MEMBERCHAT = "/member/chat";
export const CONSULTS: string = "/consults";
export const MEMBER = "/home/member";
export const NONMEMBER = "/post/login";
export const CONSULTSTEMP = "/consult-temp";
export const CONSULTSTEMP2 = "/consult-temp2";
export const NURSECONSULTS: string = "/consults2";
export const ILACATATIONCONSULTS: string = "/intial-consult";
export const DATECONSULTS: string = "/date-consults";
export const MULTIPLECLASS = "/multiple/class"
export const VIRTUALCLASSCONSULTS: string = "/virtual-consults";
export const PRIVATECLASS:any = "/private-class"
export const PRIVATECLASS2:any = "/private-class2" 
export const PREBABYBOOTCAMP:string = "/pre-baby-bootcamp"
export const PRIVATESLEEPCONSULT = "/private-sleep"
export const GIFTCARD = "/gift-card"
export const GIFTCARDPURCHASE = "/gift-card-purchase"
export const PROFILEUSER = "/user-profile"
export const EDITPROFILE = "/edit-profile"
export const  LIVEWEBINAR = "/live-webinar"
export const PODCASTQUESTION = "/podcast-Question"
export const SPONSORSHIP = "/sponsorship-collabs"
