export const GET_COMPANY_PROFILE = "GET_COMPANY_PROFILE"
export const UPDATE_COMPANY_DATA_SUCCESS = "UPDATE_COMPANY_DATA_SUCCESS"
export const UPDATE_COMPANY_PHOTO = "UPDATE_COMPANY_PHOTO"
export const SET_UPLOAD_PROGRESS = 'SET_UPLOAD_PROGRESS'