export const GET_CLIENT$SALES_REQUEST = "GET_CLIENT$SALES_REQUEST" 
export const GET_CLIENT$SALES_SUCCESS = "GET_CLIENT$SALES_SUCCESS" 
export const GET_CLIENT$SALES_FAIL = "GET_CLIENT$SALES_FAIL" 

export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST"
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS"
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL"