export const LOADING = "LOADING"

export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL";


export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"


export const CHANGE_PASSWORD = "CHANGE_PASSWORD"



export const GET_IMAGE = "GET_IMAGE"


export const GET_PERSONAL_DATA = "GET_PERSONAL_DATA"

export const UPDATE_PERSONAL_DATA = "UPDATE_PERSONAL_DATA"

export const UPDATE_PERSONAL_IMAGE = "UPDATE_PERSONAL_IMAGE"

export const GET_USER_IMAGE = "GET_USER_IMAGE"

export const FORGOT_PASSWORD = "FORGOT_PASSWORD"
export const FORGOT_RESET_PASSWORD = "FORGOT_RESET_PASSWORD"
export const AUTH_IMAGE = "AUTH_IMAGE"
export const CHECK_USENAME_UNIQUE = "CHECK_USENAME_UNIQUE"


export const GET_PROFILE_MEDIA = "GET_PROFILE_MEDIA"